Add more package analyzers
Corniel/dotnet-project-file-analyzers pull request #43
Opened 2023-07-11 19:22 UTC by CptWesley

### Changes:
- Added more analyzers for various different (semi-)popular libraries.
- Add support for language-specific package analyzers.
- Changed diagnostic reporting algorithm to pick nearest match rather than first match.

2023-07-11 19:44 UTC, Corniel commented on src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseAnalyzersForPackages.cs
> +                if (matched is { } reference)
this can be in the if statement

2023-07-11 19:45 UTC, Corniel commented on src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseAnalyzersForPackages.cs
> +                .Where(analyzer => analyzer.Language is null || analyzer.Language == context.Compilation.Options.Language)
Move to analyzer class as `IsApplicable`

2023-07-11 19:46 UTC, Corniel requested changes
The release notes should be updated, so should the documentation page of this rule. The additions overall are really nice!

2023-07-11 20:20 UTC, CptWesley commented
@Corniel updated.

2023-07-12 07:43 UTC, Corniel commented on rules/Proj1001.md
> +| Analyzer(s)                                                                                                           | Packages
I think this column should be centered. (`|:--:|`

2023-07-12 07:43 UTC, Corniel commented on src/DotNetProjectFile.Analyzers/Analyzers/MsBuild/UseAnalyzersForPackages.cs
> +                .Where(analyzer => packageReferences.None(analyzer.IsMatch));
Not it easy to merge those two statements.

2023-07-12 07:44 UTC, Corniel approved these changes
If you can change those two minor comments, it is perfectly fine!

2023-07-12 18:38 UTC, Corniel approved these changes
LGTM

2023-07-12 18:38 UTC, merged